export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';
export const BLOCK_RETRIEVAL_STATUS_START = 'BLOCK_RETRIEVAL_STATUS_START';
export const BLOCK_RETRIEVAL_STATUS_SUCCESS = 'BLOCK_RETRIEVAL_STATUS_SUCCESS';
export const BLOCK_RETRIEVAL_STATUS_FAILURE = 'BLOCK_RETRIEVAL_STATUS_FAILURE';